### ISSUE TITLE
Configuration to disable tracerresolver

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-tracerresolver#24]
This issue is created based on: https://github.com/opentracing-contrib/java-spring-web/issues/38#issuecomment-327727003

We are using tracerresolver as a fall-back mechanism to get the tracer in app configuration layes (spring boot auto-configs, wf-swarm fractions). I have a use case when I am using tracerresolver and I would like to quickly disable instrumentation. Auto-config layer returns NoopTracer if the resolved tracer is `null`. 

Would it make sense to add env/system property which would tell tracerresolver to return `null`?

**Comment by sjoerdtalsma** [comment]
I personally have no use for it, but if it's useful for others I have no objections to adding such a property.
However, as far as functionality is concerned, _disabling_ resolving might also result in the `GlobalTracer` being returned instead of `null`?
Not-setting the GlobalTracer will then also disable instrumentation by using the no-op tracer while avoiding potential NPE's.

**Comment by sjoerdtalsma** [comment]
Scratch the 'null' comments; they're to be expected by the existing resolver api anyway.
